"""Upload route business logic package."""

from services.upload.complete import complete_upload_transaction
from services.upload.hashtags import _normalize_hashtags_list, _split_tags, _to_hash_tags
from services.upload.list_detail import (
    _build_slim_upload_item,
    _dt_iso,
    build_upload_detail_payload,
    build_upload_list_item,
    compute_smart_schedule_display,
    fetch_upload_detail,
    fetch_upload_queue_stats,
    fetch_user_uploads_list,
    geo_location_hint_for_upload,
    poll_upload_thumbnails_payload,
    scene_story_from_artifacts,
    timeline_story_from_artifacts,
    youtube_copyright_shorts_notice_from_artifacts,
)
from services.upload.prefs import (
    merge_upload_init_thumbnail_preferences,
    merge_upload_init_tiktok_post_settings,
    normalize_user_prefs_snapshot,
)
from services.upload.presign import (
    estimate_upload_costs,
    presign_create_upload,
    telemetry_r2_key_for_upload,
)
from services.upload.stage_labels import STAGE_LABELS, stage_label_for
from services.upload.status import (
    ALLOWED_VIDEO_TYPES,
    COMPLETE_IDEMPOTENT_STATUSES,
    COMPLETED_STATUSES,
    FAILED_STATUSES,
    PARTIAL_STATUSES,
    PROCESSING_STATUSES,
    QUEUE_VIEW_STATUSES,
    SCHEDULED_PIPELINE_STATUSES,
    UPLOAD_STATUS_LABEL,
    UPLOAD_VIEW_STATUS,
    scheduled_in_clause,
)
from services.upload.thumbnails import (
    THUMBNAIL_REPAIR_STATUSES,
    _normalize_platform_results_detail,
    artifact_platform_thumbnail_r2_keys,
    browser_safe_thumbnail_url,
    card_thumbnail_url,
    collect_thumbnail_repair_ids,
    merged_platform_thumbnail_urls,
    mirrored_platform_thumbnail_r2_keys,
    pikzels_template_thumbnail_warning,
    platform_thumbnail_urls_from_artifacts,
    posted_thumbnail_browser_url,
    posted_thumbnail_fallback_for_upload,
    presign_upload_thumbnail_r2_key,
    repair_upload_thumbnails_batch,
    resolve_upload_thumbnail_r2_key,
    resolve_upload_thumbnail_r2_keys_ordered,
    stream_upload_thumbnail_bytes,
    thumbnail_render_method_from_artifacts,
    thumbnail_storage_missing_flag,
    upload_card_thumbnail_href,
)
from services.upload.tiktok import validate_upload_row_tiktok_settings

__all__ = [
    "ALLOWED_VIDEO_TYPES",
    "COMPLETE_IDEMPOTENT_STATUSES",
    "COMPLETED_STATUSES",
    "FAILED_STATUSES",
    "PARTIAL_STATUSES",
    "PROCESSING_STATUSES",
    "QUEUE_VIEW_STATUSES",
    "SCHEDULED_PIPELINE_STATUSES",
    "STAGE_LABELS",
    "THUMBNAIL_REPAIR_STATUSES",
    "UPLOAD_STATUS_LABEL",
    "UPLOAD_VIEW_STATUS",
    "_build_slim_upload_item",
    "_dt_iso",
    "_normalize_hashtags_list",
    "_normalize_platform_results_detail",
    "_split_tags",
    "_to_hash_tags",
    "artifact_platform_thumbnail_r2_keys",
    "browser_safe_thumbnail_url",
    "build_upload_detail_payload",
    "build_upload_list_item",
    "card_thumbnail_url",
    "collect_thumbnail_repair_ids",
    "complete_upload_transaction",
    "compute_smart_schedule_display",
    "estimate_upload_costs",
    "fetch_upload_detail",
    "fetch_upload_queue_stats",
    "fetch_user_uploads_list",
    "geo_location_hint_for_upload",
    "merge_upload_init_thumbnail_preferences",
    "merge_upload_init_tiktok_post_settings",
    "merged_platform_thumbnail_urls",
    "mirrored_platform_thumbnail_r2_keys",
    "normalize_user_prefs_snapshot",
    "pikzels_template_thumbnail_warning",
    "platform_thumbnail_urls_from_artifacts",
    "poll_upload_thumbnails_payload",
    "posted_thumbnail_browser_url",
    "posted_thumbnail_fallback_for_upload",
    "presign_create_upload",
    "presign_upload_thumbnail_r2_key",
    "repair_upload_thumbnails_batch",
    "resolve_upload_thumbnail_r2_key",
    "resolve_upload_thumbnail_r2_keys_ordered",
    "scene_story_from_artifacts",
    "scheduled_in_clause",
    "stage_label_for",
    "stream_upload_thumbnail_bytes",
    "telemetry_r2_key_for_upload",
    "thumbnail_render_method_from_artifacts",
    "thumbnail_storage_missing_flag",
    "timeline_story_from_artifacts",
    "upload_card_thumbnail_href",
    "validate_upload_row_tiktok_settings",
    "youtube_copyright_shorts_notice_from_artifacts",
]
