#!/usr/bin/env python3
"""
Guardrails for routers/: physical line count and obvious asyncpg-style DB calls.

Thin-router pattern: HTTP wiring in routers; SQL and heavy logic in services/core.
This lint uses a checked-in baseline so existing modules pass while new routers
stay small unless explicitly allowlisted.

  python tools/lint_routers.py              # verify against baseline
  python tools/lint_routers.py --write-baseline   # rewrite tools/router_lint_baseline.json from disk

CI: .github/workflows/ci.yml runs this script from the repo root.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ROUTERS = ROOT / "routers"
BASELINE_PATH = Path(__file__).resolve().parent / "router_lint_baseline.json"

# Lines that look like asyncpg (or same shape) DB work inside a route module.
_DB_LINE = re.compile(
    r"(\bawait\s+\w+\.(?:execute|fetchrow|fetchval|fetch|executemany)\s*\(|\basync\s+with\s+\w+\.transaction\s*\()",
)


def physical_lines(text: str) -> int:
    if not text:
        return 0
    return text.count("\n") + (0 if text.endswith("\n") else 1)


def db_touch_line_count(text: str) -> int:
    return sum(1 for line in text.splitlines() if _DB_LINE.search(line))


def default_caps(nlines: int, db_lines: int) -> tuple[int, int]:
    """Slack so tiny edits do not require baseline churn; tighten baseline over time."""
    max_lines = max(80, int(math.ceil(nlines * 1.04)) + 24)
    max_db = max(0, int(math.ceil(db_lines * 1.08)) + 4)
    return max_lines, max_db


def load_baseline() -> dict:
    if not BASELINE_PATH.is_file():
        print(f"Missing baseline: {BASELINE_PATH}", file=sys.stderr)
        sys.exit(2)
    return json.loads(BASELINE_PATH.read_text(encoding="utf-8"))


def write_baseline() -> None:
    data = {
        "comment": "Regenerated by tools/lint_routers.py --write-baseline. "
        "Raise caps intentionally when a router must grow; prefer extracting services.",
        "defaults": {"max_lines": 400, "max_db_touch_lines": 15},
        "files": {},
    }
    for path in sorted(ROUTERS.glob("*.py")):
        if path.name == "__init__.py":
            continue
        text = path.read_text(encoding="utf-8")
        n = physical_lines(text)
        d = db_touch_line_count(text)
        ml, md = default_caps(n, d)
        key = f"routers/{path.name}"
        data["files"][key] = {"max_lines": ml, "max_db_touch_lines": md}
    BASELINE_PATH.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {BASELINE_PATH}")


def lint() -> int:
    baseline = load_baseline()
    defaults = baseline.get("defaults") or {}
    def_max_lines = int(defaults.get("max_lines", 400))
    def_max_db = int(defaults.get("max_db_touch_lines", 15))
    files_cap: dict = baseline.get("files") or {}

    errors: list[str] = []
    seen: set[str] = set()

    for path in sorted(ROUTERS.glob("*.py")):
        if path.name == "__init__.py":
            continue
        rel = f"routers/{path.name}"
        seen.add(rel)
        text = path.read_text(encoding="utf-8")
        n = physical_lines(text)
        d = db_touch_line_count(text)
        cap = files_cap.get(rel)
        if cap:
            max_lines = int(cap["max_lines"])
            max_db = int(cap["max_db_touch_lines"])
        else:
            max_lines = def_max_lines
            max_db = def_max_db
            if n > max_lines or d > max_db:
                errors.append(
                    f"{rel}: not in baseline — {n} lines (cap {max_lines}), "
                    f"{d} db-touch lines (cap {max_db}). Add an entry to tools/router_lint_baseline.json "
                    f"or shrink the router / move SQL to services/."
                )
                continue
        if n > max_lines:
            errors.append(f"{rel}: {n} lines exceeds cap {max_lines}")
        if d > max_db:
            errors.append(f"{rel}: {d} db-touch lines exceeds cap {max_db}")

    stale = set(files_cap.keys()) - seen
    for rel in sorted(stale):
        errors.append(f"Baseline references missing file: {rel}")

    if errors:
        print("Router lint failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--write-baseline",
        action="store_true",
        help="Regenerate tools/router_lint_baseline.json from current routers/",
    )
    args = ap.parse_args()
    if args.write_baseline:
        write_baseline()
        return 0
    return lint()


if __name__ == "__main__":
    raise SystemExit(main())
